package main

// Code generated by go:generate; DO NOT EDIT.
import "embed"

//go:embed .gitignore generate_embed_list.go go.mod go.sum main.go makefile readme.md
var embedded embed.FS

func init() {
	embeddedFiles = &embedded
}
